<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150405161817 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_sync_domain_model_bond ADD name VARCHAR(255) NOT NULL, ADD uri VARCHAR(255) NOT NULL, ADD token VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE famelo_sync_domain_model_filter ADD classname VARCHAR(255) NOT NULL, ADD configuration VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE famelo_sync_domain_model_pair ADD localuuid VARCHAR(255) NOT NULL, ADD remoteuuid VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_sync_domain_model_bond DROP name, DROP uri, DROP token");
		$this->addSql("ALTER TABLE famelo_sync_domain_model_filter DROP classname, DROP configuration");
		$this->addSql("ALTER TABLE famelo_sync_domain_model_pair DROP localuuid, DROP remoteuuid");
	}
}