<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150405160355 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_sync_domain_model_bond (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_sync_domain_model_filter (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_sync_domain_model_pair (persistence_object_identifier VARCHAR(40) NOT NULL, bond VARCHAR(40) DEFAULT NULL, INDEX IDX_2C830E42418FE1 (bond), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_sync_domain_model_pair ADD CONSTRAINT FK_2C830E42418FE1 FOREIGN KEY (bond) REFERENCES famelo_sync_domain_model_bond (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_sync_domain_model_pair DROP FOREIGN KEY FK_2C830E42418FE1");
		$this->addSql("DROP TABLE famelo_sync_domain_model_bond");
		$this->addSql("DROP TABLE famelo_sync_domain_model_filter");
		$this->addSql("DROP TABLE famelo_sync_domain_model_pair");
	}
}